### ISSUE TITLE
Is it possible to rip the data from the games?

### ISSUE THREAD

**Issue by TheT113** [GreenGhost21/BG-Scripts-and-Resources#1]
Heya, I wasn't sure how else to message you about this so I figured I'd just post about it as an Issue here.

I was thinking about, a possible way to create the BGChanges "smarter, not harder", and wondered: is it possible to look at the code for individual games, and see how they are set to call the videos, so we can make note of their timing and copy that, instead of eyeballing the gameplay?

This would make it much easier to batch convert entire games, if it were possible. Do we know anyone (the people who rip the videos from the games) who can look into that sort of thing?

A separate thing I wanted to bring up, that I don't think I need to make a new "Issue" about: There are upscaled versions of the MAX-Extreme videos out there, it may be worth looking into/compiling those; I personally use (a version of) them and prefer them to the lower scale versions, but I don't remember where I got them and trying to find them I've now found more than one. (I can link that if you need it, it was on zenius).

**Comment by GreenGhost21** [comment]
Sorry for taking so long to check back in, I've been very busy with other stuff, including a clean reinstall of my PC's OS.

On your first point, I am somewhat familiar with extracting some data from the Xbox games (from UM2 onwards), so at least I have that as a basis for my Ultramix scripts (and possibly Universe scripts down the line). However, extracting the needed files is a tedious process that involves copying raw data and pasting it into new files via a hex editor. Even then, I only get CSV files that I can only use as a basis for manually creating the scripts. If you can figure out a way to translate the CSV files to the BGScripts format that StepMania uses, I'd be more than happy to share some of the files I've extracted thus far with you, _so long as you actually own the games in question_. I do not approve of piracy, and used physical copies of the games are pretty cheap anyways.

As for your separate point: If you're referring to Cuzco's versions of the videos, I'm somewhat familiar with them, and I remember investigating using them in the past. However, what made me decide against using them is that the set is incomplete versus the originals (last I checked, anyways), and some of the videos are not true enough to the originals for my personal preference. 

If you are referring to someone else's version of upscaled videos, send me a link, as I am _highly_ interested.

As for this project, I am going to try to work on it some more. However between work and other personal projects, I can't guarantee any consistency.

**Comment by GreenGhost21** [comment]
So, seeing as there's been no reply within two months, I'm going to close this. 

For the record, I _did_ find upscaled versions of the videos on the ZIv forums. Two versions, actually.
